# Generated by Django 6.0.6 on 2026-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['latitude', 'longitude', 'retail_price'], name='idx_latlon_price'),
        ),
    ]
